config/routes.rb
Rails.application.routes.draw do
  resources :matches
  resources :players
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "players#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/match.rb
class Match < ApplicationRecord
  store :result, accessors: [:winner_name, :loser_name, :winner_id, :loser_id]
  has_and_belongs_to_many :players
     # belongs_to :winner, class_name: 'Player'
     # belongs_to :loser, class_name: 'Player'

  after_save :set_ranking

  def set_ranking
   	self.players.each do |player|
      # winning_matches = player.matches.map(&:winner_id).count(player.id)

      winning_matches =player.matches.group_by(&:winner_name).transform_values(&:count)
      p winning_matches
      sorted_winnes = winning_matches.sort_by { |_element, count| -count }
      current_rank = 1
      sorted_winnes.each_with_index do |(element, count), index|
  
        if index > 0 && sorted_winnes[index - 1][1] != count
          current_rank = index + 1
        end
        player.rank = current_rank
        player.save!
      end  
    end  
  end
end

app/models/player.rb
class Player < ApplicationRecord
  validates :name, presence: true
  

  has_and_belongs_to_many :matches
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  before_action :set_match, only: %i[ show edit update destroy ]

  # GET /matches or /matches.json
  def index
    @matches = Match.all
  end

  # GET /matches/1 or /matches/1.json
  def show
  end

  # GET /matches/new
  def new
    @match = Match.new
    @players = Player.all
  end

  # GET /matches/1/edit
  def edit
    @players = Player.all
  end

  # POST /matches or /matches.json
  def create
    @match = Match.new(match_params)

    respond_to do |format|
      if @match.save
        @match.player_ids = params[:match][:player_ids] if params[:match][:player_ids].present?
        format.html { redirect_to @match, notice: "Match was successfully created." }
        format.json { render :show, status: :created, location: @match }
      else
        @@players = Player.all
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /matches/1 or /matches/1.json
  def update
    binding.pry
    respond_to do |format|
      if @match.update(match_params)
        format.html { redirect_to @match, notice: "Match was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @match }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /matches/1 or /matches/1.json
  def destroy
    @match.destroy!

    respond_to do |format|
      format.html { redirect_to matches_path, notice: "Match was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_match
      @match = Match.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def match_params
      # params.expect(match: [ :code, :name, :winner_name, :loser_name, :winner_id, :loser_id, player_ids: []])

      params.require(:match).permit(
      :code, :name, :winner_name, :loser_name, :winner_id, :loser_id, player_ids: []
    )
    end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :set_player, only: %i[ show edit update destroy ]

  # GET /players or /players.json
  def index
    @players = Player.all
  end

  # GET /players/1 or /players/1.json
  def show
  end

  # GET /players/new
  def new
    @player = Player.new
  end

  # GET /players/1/edit
  def edit
  end

  # POST /players or /players.json
  def create
    @player = Player.new(player_params)

    respond_to do |format|
      if @player.save
        format.html { redirect_to @player, notice: "Player was successfully created." }
        format.json { render :show, status: :created, location: @player }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /players/1 or /players/1.json
  def update
    respond_to do |format|
      if @player.update(player_params)
        format.html { redirect_to @player, notice: "Player was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @player }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /players/1 or /players/1.json
  def destroy
    @player.destroy!

    respond_to do |format|
      format.html { redirect_to players_path, notice: "Player was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_player
      @player = Player.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def player_params
      params.expect(player: [ :name, :rank, match_ids: [] ])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Badmiton" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/matches/_form.html.erb
<%= form_with(model: match) do |form| %>
  <% if match.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(match.errors.count, "error") %> prohibited this match from being saved:</h2>

      <ul>
        <% match.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :code, style: "display: block" %>
    <%= form.number_field :code %>
  </div>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :players %>
    <% @players.each do |player| %>
      <div>
        <%= check_box_tag "match[player_ids][]", player.id, @match.players.include?(player), id: "match_player_ids_#{player.id}" %>
        <%= label_tag "match_player_ids_#{player.id}", player.name %>
      </div>
    <% end %>
  </div>

  <div>
    <%= form.label :Winner, style: "display: block" %>
    <%  @match.players.each do |player| %>
      <div>
        <%= radio_button_tag :winner_name, player.id, id: "match_player_winner_ids_#{player.id}" %>
          <%= label_tag "match_player_ids_#{player.id}", player.name%>
      </div>
    <% end %>
  </div>
  
   <div>
    <%= form.label :Runner, style: "display: block" %>
    <%  @match.players.each do |player| %>
      <div>
        <%= radio_button_tag :loser_name, player.id, id: "match_player_loser_ids_#{player.id}" %>
          <%= label_tag "match_player_ids_#{player.id}", player.name%>
      </div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/matches/_match.html.erb
<div id="<%= dom_id match %>">
  <p>
    <strong>Code:</strong>
    <%= match.code %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= match.name %>
  </p>

  <p>
    <strong>Result:</strong>
    Winner : <%= match.winner_name %>
    Loser  : <%= match.loser_name %>
  </p>

</div>

app/views/matches/edit.html.erb
<% content_for :title, "Editing match" %>

<h1>Editing match</h1>

<%= render "form", match: @match %>

<br>

<div>
  <%= link_to "Show this match", @match %> |
  <%= link_to "Back to matches", matches_path %>
</div>

app/views/matches/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Matches" %>

<h1>Matches</h1>

<div id="matches">
  <% @matches.each do |match| %>
    <%= render match %>
    <% if match.players.any? %>
        Players: <%= match.players.map(&:name).join(', ') %>
    <% end %>
    <p>
      <%= link_to "Show this match", match %>
    </p>
  <% end %>
</div>

<%= link_to "New match", new_match_path %>

app/views/matches/new.html.erb
<% content_for :title, "New match" %>

<h1>New match</h1>

<%= render "form", match: @match %>

<br>

<div>
  <%= link_to "Back to matches", matches_path %>
</div>

app/views/matches/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @match %>

<div>
  <%= link_to "Edit this match", edit_match_path(@match) %> |
  <%= link_to "Back to matches", matches_path %>

  <%= button_to "Destroy this match", @match, method: :delete %>
</div>

app/views/players/_form.html.erb
<%= form_with(model: player) do |form| %>
  <% if player.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(player.errors.count, "error") %> prohibited this player from being saved:</h2>

      <ul>
        <% player.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :rank, style: "display: block" %>
    <%= form.number_field :rank %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/players/_player.html.erb
<div id="<%= dom_id player %>">
  <p>
    <strong>Name:</strong>
    <%= player.name %>
  </p>

  <p>
    <strong>Rank:</strong>
    <%= player.rank %>
  </p>

</div>

app/views/players/edit.html.erb
<% content_for :title, "Editing player" %>

<h1>Editing player</h1>

<%= render "form", player: @player %>

<br>

<div>
  <%= link_to "Show this player", @player %> |
  <%= link_to "Back to players", players_path %>
</div>

app/views/players/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Players" %>

<h1>Players</h1>

<div id="players">
  <% @players.each do |player| %>
    <%= render player %>
     <% if player.matches.any? %>
        (Matches Played: <%= player.matches.map(&:name).join(', ') %>)
      <% else %>
        No Match Played
      <% end %>
    <p>
      <%= link_to "Show this player", player %>
    </p>
  <% end %>
</div>

<%= link_to "New player", new_player_path %>

app/views/players/new.html.erb
<% content_for :title, "New player" %>

<h1>New player</h1>

<%= render "form", player: @player %>

<br>

<div>
  <%= link_to "Back to players", players_path %>
</div>

app/views/players/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @player %>

<div>
  <%= link_to "Edit this player", edit_player_path(@player) %> |
  <%= link_to "Back to players", players_path %>

  <%= button_to "Destroy this player", @player, method: :delete %>
</div>